### ISSUE TITLE
Project cannot be cast to sbt.BasicScalaPaths

### ISSUE THREAD

**Issue by andreasW** [musk/SbtEclipsify#16]
With 0.7.0 instead of 0.4.0, it downloaded the package with no problems, and the rest of the instructions are quite precise. However, I am not quite there yet. Trying to eclipsify the "reactive" framework by nafg (https://github.com/nafg), I ran into the following issue:

andreas@Univac:~/trunk/reactive$ sbt eclipse
[warn] Credentials file /private/nafg/.credentials does not exist
[warn] Credentials file /private/nafg/.credentials does not exist
[info] Building project reactive-parent 0.0.1-SNAPSHOT against Scala 2.8.1
[info]    using Project with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == eclipse ==
[info] Creating eclipse project...
java.lang.ClassCastException: Project cannot be cast to sbt.BasicScalaPaths
    at de.element34.sbteclipsify.ClasspathFile.writeFile(ClasspathFile.scala:67)
    at de.element34.sbteclipsify.Eclipsify$class.writeClasspathFile(SbtEclipsify.scala:71)
    at Project.writeClasspathFile(Project.scala:23)
    at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(SbtEclipsify.scala:43)
    at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(SbtEclipsify.scala:40)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.run(RunTask.scala:32)
    at sbt.impl.RunTask$.apply(RunTask.scala:17)
    at sbt.impl.RunTask$.apply(RunTask.scala:16)
    at sbt.Project$class.run(Project.scala:98)
    at sbt.Project$class.act(Project.scala:129)
    at sbt.ParentProject.act(BasicProjectTypes.scala:568)
    at sbt.xMain$$anonfun$8.apply(Main.scala:512)
    at sbt.xMain$$anonfun$8.apply(Main.scala:512)
    at sbt.xMain.withAction(Main.scala:545)
    at sbt.xMain.sbt$xMain$$handleAction(Main.scala:512)
    at sbt.xMain.handleCommand(Main.scala:502)
    at sbt.xMain.processAction(Main.scala:441)
    at sbt.xMain.process$1(Main.scala:257)
    at sbt.xMain.processArguments(Main.scala:266)
    at sbt.xMain.startProject(Main.scala:107)
    at sbt.xMain.run(Main.scala:84)
    at sbt.xMain.run0$1(Main.scala:35)
    at sbt.xMain.run(Main.scala:42)
    at xsbt.boot.Launch$.run(Launch.scala:53)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$.launch(Launch.scala:57)
    at xsbt.boot.Launch$.explicit(Launch.scala:42)
    at xsbt.boot.Launch$.initialized(Launch.scala:38)
    at xsbt.boot.Launch$.parsed(Launch.scala:31)
    at xsbt.boot.Launch$.configured(Launch.scala:21)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Launch$.apply(Launch.scala:13)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.run(Boot.scala:19)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[info] == eclipse ==
[error] Error running eclipse: java.lang.ClassCastException: Project cannot be cast to sbt.BasicScalaPaths
[info] 
[info] Total time: 0 s, completed May 26, 2011 8:53:18 AM
[info] 
[info] Total session time: 1 s, completed May 26, 2011 8:53:18 AM
[error] Error during build.
andreas@Univac:~/trunk/reactive$ ^C
andreas@Univac:~/trunk/reactive$ sbt eclipse
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[error] /home/andreas/Documents/Source/trunk/reactive/project/build/Project.scala:23: class Project needs to be abstract, since method testResourcesPath in trait BasicScalaPaths of type => sbt.PathFinder is not defined
[error] class Project(info: ProjectInfo) extends ParentProject(info) with Eclipsify with BasicScalaPaths {
[error]       ^
[error] one error found
Compilation failed

 Hit enter to retry or 'exit' to quit: 

A version thing, perhaps? I am stumped...

Andreas

**Comment by musk** [comment]
I will check this. If you are willing to try could you get the
0.8.0-SNAPSHOT branch from github and build it locally and check if
that version gives you the same error? I haven't managed to deploy a
0.8.0-Snapshot version yet as I'm still trying to integrate some
changes from szeiger into the 0.8.0 branch.

You basically need to clone the 0.8.0 branch and then build using sbt
publish-local

After that you can use 0.8.0-SNAPSHOT as the version for sbt-eclipsify.

-Stefan

2011/5/26 andreasW
reply@reply.github.com:

**Comment by andreasW** [comment]
I tried this. I succeeded with 

git clone https://github.com/musk/SbtEclipsify.git
cd SbtEclipsify
git checkout -b 0.8.0

but then failed with:

andreas@Univac:~/trunk/SbtEclipsify$ sbt publish-local
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/15ms)
Getting Scala 2.7.7 ...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (9911kB/19ms)
Getting org.scala-tools.sbt sbt_2.7.7 0.7.4 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    15 artifacts copied, 0 already retrieved (4096kB/21ms)
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] 
[info] Updating plugins...
[warn]  module not found: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/andreas/.ivy2/local/de.element34/sbt-eclipsify/0.7.1-SNAPSHOT/ivys/ivy.xml
[warn]   -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]   /home/andreas/.ivy2/local/de.element34/sbt-eclipsify/0.7.1-SNAPSHOT/jars/sbt-eclipsify.jar
[warn] ==== t_repo: tried
[warn]   http://tristanhunt.com:8081/content/groups/public/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]   -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]   http://tristanhunt.com:8081/content/groups/public/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]   -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]   http://repo1.maven.org/maven2/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]   -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]   http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[info] downloading http://scala-tools.org/repo-releases/net/databinder/posterous-sbt/0.1.4/posterous-sbt-0.1.4.jar ...
[info]  [SUCCESSFUL ] net.databinder#posterous-sbt;0.1.4!posterous-sbt.jar (109ms)
[info] downloading http://tristanhunt.com:8081/content/groups/public/com/tristanhunt/knockoff_2.7.7/0.6.1-9/knockoff_2.7.7-0.6.1-9.jar ...
[info]  [SUCCESSFUL ] com.tristanhunt#knockoff_2.7.7;0.6.1-9!knockoff_2.7.7.jar (658ms)
[info] downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-http_2.7.7/0.7.0/dispatch-http_2.7.7-0.7.0.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-http_2.7.7;0.7.0!dispatch-http_2.7.7.jar (677ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-tools/testing/scalatest/0.9.5/scalatest-0.9.5.jar ...
[info]  [SUCCESSFUL ] org.scala-tools.testing#scalatest;0.9.5!scalatest.jar (757ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.0.1!httpclient.jar (494ms)
[info] downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-futures_2.7.7/0.7.0/dispatch-futures_2.7.7-0.7.0.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-futures_2.7.7;0.7.0!dispatch-futures_2.7.7.jar (224ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.0.1!httpcore.jar (199ms)
[info] downloading http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ...
[info]  [SUCCESSFUL ] commons-logging#commons-logging;1.1.1!commons-logging.jar (128ms)
[info] downloading http://repo1.maven.org/maven2/commons-codec/commons-codec/1.3/commons-codec-1.3.jar ...
[info]  [SUCCESSFUL ] commons-codec#commons-codec;1.3!commons-codec.jar (261ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[warn] :: problems summary ::
[warn] :::: WARNINGS
[warn]      module not found: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT
[warn]  ==== local: tried
[warn]    /home/andreas/.ivy2/local/de.element34/sbt-eclipsify/0.7.1-SNAPSHOT/ivys/ivy.xml
[warn]    -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]    /home/andreas/.ivy2/local/de.element34/sbt-eclipsify/0.7.1-SNAPSHOT/jars/sbt-eclipsify.jar
[warn]  ==== t_repo: tried
[warn]    http://tristanhunt.com:8081/content/groups/public/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]    -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]    http://tristanhunt.com:8081/content/groups/public/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[warn]  ==== public: tried
[warn]    http://repo1.maven.org/maven2/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]    -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]    http://repo1.maven.org/maven2/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[warn]  ==== Scala-Tools Maven2 Repository: tried
[warn]    http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.pom
[warn]    -- artifact de.element34#sbt-eclipsify;0.7.1-SNAPSHOT!sbt-eclipsify.jar:
[warn]    http://scala-tools.org/repo-releases/de/element34/sbt-eclipsify/0.7.1-SNAPSHOT/sbt-eclipsify-0.7.1-SNAPSHOT.jar
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[info] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT: not found
sbt.ResolveException: unresolved dependency: de.element34#sbt-eclipsify;0.7.1-SNAPSHOT: not found

**Comment by andreasW** [comment]
Looking for the source of the "not found" version, I found:

andreas@Univac:~/trunk/SbtEclipsify$ grep 0.7.1 _/_/*
project/plugins/Plugins.scala:  lazy val eclipse = "de.element34" % "sbt-eclipsify" % "0.7.1-SNAPSHOT"

I changed the dependency to 0.7.0, but then got another error, apparently related to scalatest:

andreas@Univac:~/trunk/SbtEclipsify$ sbt publish-local
[info] Recompiling plugin definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] 
[info] Updating plugins...
[info] :: retrieving :: plugin-definition#plugin-definition_2.7.7 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, javadoc]
[info]  10 artifacts copied, 0 already retrieved (2001kB/30ms)
[success] Plugins updated successfully.
[info] 
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/sbt-eclipsify-0.7.0.jar ...
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/posterous-sbt-0.1.4.jar ...
[info] Recompiling plugin...
[info]    Source analysis: 8 new/modified, 0 indirectly invalidated, 0 removed.
[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[warn] Credentials file /home/andreas/.credentials does not exist
[info] Building project sbt-eclipsify 0.8.0-SNAPSHOT against Scala 2.7.7
[info]    using SbtEclipsifyPluginProject with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == compile ==
[info]   Source analysis: 7 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] Compilation successful.
[info]   Post-analysis: 79 classes.
[info] == compile ==
[info] 
[info] == copy-resources ==
[info] == copy-resources ==
[info] 
[info] == copy-test-resources ==
[info] == copy-test-resources ==
[info] 
[info] == test-compile ==
[info]   Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling test sources...
[error] /home/andreas/Documents/Source/trunk/SbtEclipsify/src/test/scala/de/element34/sbteclipsify/ClasspathFileTest.scala:33: value scalatest is not a member of package org
[error] import org.scalatest._
[error]            ^
[error] /home/andreas/Documents/Source/trunk/SbtEclipsify/src/test/scala/de/element34/sbteclipsify/ClasspathFileTest.scala:40: value should is not a member of java.lang.String
[error]   "A ClasspathEntry" should "produce the xml for a classpathentry in the elcipse .classpath file" in {
[error]                      ^
[error] two errors found
[info] == test-compile ==
[error] Error running test-compile: Compilation failed
[info] 
[info] Total time: 2 s, completed May 26, 2011 10:33:27 AM
[info] 
[info] Total session time: 11 s, completed May 26, 2011 10:33:27 AM
[error] Error during build.

**Comment by andreasW** [comment]
I figured: Well, probably a missing dependency (although it appears to be right there in project/build/project), and downloaded scalatest-1.2.jar, dropping it into the "lib" directory. This is when things got really weird:

[info] Recompiling project definition...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[warn] Credentials file /home/andreas/.credentials does not exist
[info] Building project sbt-eclipsify 0.8.0-SNAPSHOT against Scala 2.7.7
[info]    using SbtEclipsifyPluginProject with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == compile ==
[info]   Source analysis: 0 new/modified, 0 indirectly invalidated, 0 removed.
[info] Compiling main sources...
[info] Nothing to compile.
[info]   Post-analysis: 79 classes.
[info] == compile ==
[info] 
[info] == copy-resources ==
[info] == copy-resources ==
[info] 
[info] == test-compile ==
[info]   Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[info] == test-compile ==
java.lang.NoClassDefFoundError: scala/collection/Seq
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at sbt.TestFramework.create(TestFramework.scala:31)
    at sbt.BasicScalaProject$BaseCompileConfig$$anonfun$getFingerprints$1.apply(DefaultProject.scala:212)
    at sbt.BasicScalaProject$BaseCompileConfig$$anonfun$getFingerprints$1.apply(DefaultProject.scala:212)
    at scala.List.flatMap(List.scala:1132)
    at scala.List.flatMap(List.scala:452)
    at sbt.BasicScalaProject$BaseCompileConfig.getFingerprints(DefaultProject.scala:212)
    at sbt.BasicScalaProject$TestCompileConfig.fingerprints(DefaultProject.scala:241)
    at sbt.CompileConditional$CompileAnalysisCallback.<init>(Conditional.scala:222)
    at sbt.CompileConditional.analysisCallback(Conditional.scala:219)
    at sbt.CompileConditional.analysisCallback(Conditional.scala:213)
    at sbt.AbstractCompileConditional.execute(Conditional.scala:344)
    at sbt.Conditional$class.run(Conditional.scala:43)
    at sbt.AbstractCompileConditional.run(Conditional.scala:231)
    at sbt.BasicScalaProject.sbt$BasicScalaProject$$doCompile(DefaultProject.scala:259)
    at sbt.BasicScalaProject$$anonfun$testCompileAction$1.apply(DefaultProject.scala:274)
    at sbt.BasicScalaProject$$anonfun$testCompileAction$1.apply(DefaultProject.scala:274)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Control$.trapUnit(Control.scala:19)
    at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at sbt.TestFramework.create(TestFramework.scala:31)
    at sbt.BasicScalaProject$BaseCompileConfig$$anonfun$getFingerprints$1.apply(DefaultProject.scala:212)
    at sbt.BasicScalaProject$BaseCompileConfig$$anonfun$getFingerprints$1.apply(DefaultProject.scala:212)
    at scala.List.flatMap(List.scala:1132)
    at scala.List.flatMap(List.scala:452)
    at sbt.BasicScalaProject$BaseCompileConfig.getFingerprints(DefaultProject.scala:212)
    at sbt.BasicScalaProject$TestCompileConfig.fingerprints(DefaultProject.scala:241)
    at sbt.CompileConditional$CompileAnalysisCallback.<init>(Conditional.scala:222)
    at sbt.CompileConditional.analysisCallback(Conditional.scala:219)
    at sbt.CompileConditional.analysisCallback(Conditional.scala:213)
    at sbt.AbstractCompileConditional.execute(Conditional.scala:344)
    at sbt.Conditional$class.run(Conditional.scala:43)
    at sbt.AbstractCompileConditional.run(Conditional.scala:231)
    at sbt.BasicScalaProject.sbt$BasicScalaProject$$doCompile(DefaultProject.scala:259)
    at sbt.BasicScalaProject$$anonfun$testCompileAction$1.apply(DefaultProject.scala:274)
    at sbt.BasicScalaProject$$anonfun$testCompileAction$1.apply(DefaultProject.scala:274)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Control$.trapUnit(Control.scala:19)
    at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)
[info] 
[info] == copy-test-resources ==
[info] == copy-test-resources ==
[error] Error running test-compile: java.lang.NoClassDefFoundError: scala/collection/Seq
[info] 
[info] Total time: 0 s, completed May 26, 2011 10:45:12 AM
[info] 
[info] Total session time: 4 s, completed May 26, 2011 10:45:12 AM
[error] Error during build.

I definitely need help....

Andreas

**Comment by musk** [comment]
You can simply eliminate the dependecy for sbt-eclipsify. As you are
not planning to edit it with eclipse. Basically delete the
Plugins.scala file and you should be good to go.

I didn't even realize that I have a snapshot dependency in there.

-Stefan

2011/5/26 andreasW
reply@reply.github.com:

**Comment by andreasW** [comment]
I did that, and "compile" works well, but upon "publish-local" I still get the same error as the one in my previous post, the weird one with "NoClassDefFoundError: scala/collection/Seq"

Andreas

**Comment by andreasW** [comment]
This, of course, was a version mismatch, which I corrected (Sorry, forgot the specifics, I think it was the wrong Scala version I used)

**Comment by alexblack** [comment]
I'm hitting the same issue with 0.7.0 (java.lang.ClassCastException: Project cannot be cast to sbt.BasicScalaPaths), so I built eclipsify 0.8 as you mentioned (see http://code.alexblack.ca/building-eclipsify-080-for-use-with-sbt-077) and now I get a different exception, any ideas?

(fyi, I'm trying to use Eclipsify with Lift, see http://code.alexblack.ca/configuring-eclipsify-08-with-liftweb-aka-lif)

[info] Creating eclipse project...
java.lang.ClassCastException: LiftFrameworkProject cannot be cast to sbt.MavenStyleScalaPaths
    at de.element34.sbteclipsify.ClasspathFile.getJavaPaths(ClasspathFile.scala:240)
    at de.element34.sbteclipsify.ClasspathFile.buildEntries(ClasspathFile.scala:105)
    at de.element34.sbteclipsify.ClasspathFile.writeFile(ClasspathFile.scala:67)
    at de.element34.sbteclipsify.Eclipsify$class.writeClasspathFile(Eclipsify.scala:69)
    at LiftFrameworkProject.writeClasspathFile(LiftFrameworkProject.scala:24)
    at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(Eclipsify.scala:43)
    at de.element34.sbteclipsify.Eclipsify$$anonfun$eclipse$1.apply(Eclipsify.scala:40)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.run(RunTask.scala:32)
    at sbt.impl.RunTask$.apply(RunTask.scala:17)
    at sbt.impl.RunTask$.apply(RunTask.scala:16)
    at sbt.Project$class.run(Project.scala:98)
    at sbt.Project$class.act(Project.scala:129)
    at sbt.ParentProject.act(BasicProjectTypes.scala:559)
    at sbt.xMain$$anonfun$8.apply(Main.scala:530)
    at sbt.xMain$$anonfun$8.apply(Main.scala:530)
    at sbt.xMain.withAction(Main.scala:563)
    at sbt.xMain.sbt$xMain$$handleAction(Main.scala:530)
    at sbt.xMain.handleCommand(Main.scala:520)
    at sbt.xMain.processAction(Main.scala:459)
    at sbt.xMain.process$1(Main.scala:257)
    at sbt.xMain.processArguments(Main.scala:266)
    at sbt.xMain.startProject(Main.scala:107)
    at sbt.xMain.run(Main.scala:84)
    at sbt.xMain.run0$1(Main.scala:35)
    at sbt.xMain.run(Main.scala:42)
    at xsbt.boot.Launch$.run(Launch.scala:53)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$.launch(Launch.scala:57)
    at xsbt.boot.Launch$.explicit(Launch.scala:42)
    at xsbt.boot.Launch$.initialized(Launch.scala:38)
    at xsbt.boot.Launch$.parsed(Launch.scala:31)
    at xsbt.boot.Launch$.configured(Launch.scala:21)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Launch$.apply(Launch.scala:13)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.run(Boot.scala:19)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[info] == eclipse ==
[error] Error running eclipse: java.lang.ClassCastException: LiftFrameworkProject cannot be cast to sbt.MavenStyleScalaPaths
[info] 
[info] Total time: 1 s, completed 12-Nov-2011 12:25:40 PM
[info] 
[info] Total session time: 10 s, completed 12-Nov-2011 12:25:40 PM
